---
command: cd projects/workflow-automation-engine/source/snapshots/master/ && ./autogen.sh
command_tests:
  - description: Can we generate configure scripts?
    tags:
      - manual
    wait: 1
    white_space: convert seen 0a to 0d 0a newlines
description: generating configure scripts
tags:
  - manual
