---
command: cd projects/workflow-automation-engine/source/snapshots/master/ && ./configure
command_tests:
  - description: Can we configure the workflow automation engine source code?
    read: |
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a race-free mkdir -p... /usr/bin/mkdir -p
      checking for gawk... gawk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking whether we build universal binaries.... no
      checking OS specifics...... Host is running .
      checking for perl5... no
      checking for perl... perl
      checking Checking the perl module installation path...  ${prefix}/share/perl/5.36.0 
      checking for mtn... no
      checking for monotone... no
      checking for dpkg-buildpackage... dpkg-buildpackage
      checking for dh... no
      checking for rpmbuild... no
      checking for python... no
      checking for python2... no
      checking for python3... /usr/bin/python3
      checking for python version... 3.11
      checking for python platform... linux
      checking for GNU default python prefix... ${prefix}
      checking for GNU default python exec_prefix... ${exec_prefix}
      checking for python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.11/site-packages
      checking for python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.11/site-packages
      checking Python prefix is ... '${prefix}'
      find: 'vigilia/data': No such file or directory
      checking that generated files are newer than configure... done
      : creating ./config.status
      config.status: creating Makefile
      config.status: creating perl/Makefile
    tags:
      - manual
    timeout: 5
    white_space: convert seen 0a to 0d 0a newlines
description: configuring the source code
tags:
  - manual
